### ISSUE TITLE
design tweak?

### ISSUE THREAD

**Issue by simonbuehler** [saadj55/filament-copyable#1]
hi,

great idea, but from a UX viewpoint , it would be great if the icon would show on hovering the field/column and be the "copy" icon was centered vertically like here on github where one can copy e.g. the compoer install command,

**Comment by a21ns1g4ts** [comment]
![Peek 2022-07-30 11-29](https://user-images.githubusercontent.com/11599205/181918924-a64020ca-5b97-417a-8510-40f7693ce951.gif)

**Comment by simonbuehler** [comment]
@a21ns1g4ts  see #6

**Comment by saadj55** [comment]
#6 Merged, closing
