### ISSUE TITLE
Console Errors and Button not Handles Copy

### ISSUE THREAD

**Issue by Biostate** [saadj55/filament-copyable#8]
Hi, I installed this package on my Laravel 9, Filament 2.0 project and it's not working. I get this console errors:
![resim_2022-09-06_161429560](https://user-images.githubusercontent.com/5051330/188644651-fdc850e4-1b97-42d4-93ce-93d612761582.png)

I followed the steps on read me.

**Comment by saadj55** [comment]
Hello, please see #2  to fix this issue.

**Comment by saadj55** [comment]
First error is fixed in https://github.com/saadj55/filament-copyable/releases/tag/v0.1.2 Thanks for reporting.
